services:
  database:
    image: postgres
    container_name: ecommerce-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=secret
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
volumes:
  postgres-data:
